import React from "react";
import AnimationRevealPage from "helpers/AnimationRevealPage.js";
import { Container, ContentWithPaddingXl } from "components/misc/Layouts";
import tw from "twin.macro";
import styled from "styled-components";
import { css } from "styled-components/macro"; //eslint-disable-line
import { SectionHeading } from "components/misc/Headings";

const HeadingRow = tw.div`flex`;
const Heading = tw(SectionHeading)`text-gray-900 mb-10`;
const Text = styled.div`
  ${tw`text-lg  text-gray-800`}
  p {
    ${tw`mt-2 leading-loose`}
  }
  h1 {
    ${tw`text-3xl font-bold mt-10`}
  }
  h2 {
    ${tw`text-2xl font-bold mt-8`}
  }
  h3 {
    ${tw`text-xl font-bold mt-6`}
  }
  ul {
    ${tw`list-disc list-inside`}
    li {
      ${tw`ml-2 mb-3`}
      p {
        ${tw`mt-0 inline leading-normal`}
      }
    }
  }
`;
export default ({ headingText = "Privacy Policy" }) => {
  return (
    <AnimationRevealPage>
      <Container>
        <ContentWithPaddingXl>
          <HeadingRow>
            <Heading>{headingText}</Heading>
          </HeadingRow>
          <Text>
            <p>Last updated: April, 2022</p>

            <h2>Data Privacy Policy</h2>
            <p>
              With Appt Jobs you have Trust, Trust that we will provide you with
              the best services and Trust that we will protect the Data you
              provide to us. This Privacy Policy outlines how users’ personal
              information is used and for what purposes, and what measures are
              taken by the Company to protect the information.
            </p>

            <h2>Descriptions</h2>
            <p>
              <strong>Account: </strong>means a unique account created for you
              to access our Service or parts of our Service. <br />
              <strong>Device: </strong>means any device that can access the
              service such as a computer, a cellphoone or a digital tablet.{" "}
              <br />
              <strong>Seekers: </strong>means individuals who access the site or
              seek the services of Appt Jobs for the purpose of applying for
              jobs. <br />
              <strong>Employers/Hunters: </strong>means userss who access the
              site or seek the services of Appt Jobs for the purpose of hiring
              seekers. <br />
              <strong>Company: </strong>referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement refers to Appt Jobs. <br />
              <strong>Personal Data: </strong>means company or individual
              information provided byusers in the curse of using our services{" "}
              <br />
              <strong>Personal Data: </strong>means company or individual
              information provided by users in the course of using our services.{" "}
              <br />
              <strong>Usage Data: </strong>refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit). <br />
              <strong>You: </strong>means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable{" "}
              <br />
            </p>

            <h2>Collecting and Using Your Personal Data</h2>
            <p>
              Appt Jobs does not, and never will, rent or sell your personal
              data to any third party for any purpose (including advertising or
              marketing purposes) nor do we, or will we, permit targeted
              advertising on our Service. We only share personal information
              with third party service providers under limited circumstances as
              described in the section below. <br />
              <ol type="1" start="1">
                <li>
                  <h3>Personal information (seekers)</h3>
                  <p>
                    To make use of our service, we may ask you to provide
                    personal details during the One-on-One chat on the WhatsApp
                    platform. These details may include but are not limited to
                    the following: <br />
                    <ul>
                      <li>Name</li>
                      <li>Email Address</li>
                      <li>Phone number</li>
                      <li>Educational Qualification</li>
                    </ul>
                  </p>
                </li>
                <li>
                  <h3>Company information (Employers)</h3>
                  <p>
                    In providing you with our service, we may ask you to provide
                    certain details by filling a form on our website for
                    identification purposes. These details may include but are
                    not restricted to the following: <br />
                    <ul>
                      <li>Company Name/description</li>
                      <li>Comapany Contact</li>
                      <li>Job title</li>
                      <li>Location (state)</li>
                    </ul>
                  </p>
                </li>
              </ol>
            </p>

            <h2>Use of Collected Data</h2>
            <p>
              The company may use the above data for the following purposes{" "}
              <br />
              <ol>
                <li>
                  <strong>To provide and maintain our Service,</strong>{" "}
                  including to monitor the usage of our service, to send curated
                  and matching vacancies in line with the user job/career
                  interest, to group our customers in our database for the
                  purpose of categorization to aid the provision of our services
                </li>
                <li>
                  <strong>To manage your account: </strong>to manage your
                  registration as a user of the service. The personal Data you
                  provide can give you access to different functionalities of
                  the service that are available to you as a registered user
                </li>
                <li>
                  <strong>To provide you</strong> with news, career
                  opportunities, insights and general information about career
                  development related goods, services and events which we and
                  otoher organizations/institutions offer that are simmilar to
                  those that you have interest in or enquired about unless you
                  have opted not to receive such information.
                </li>
                <li>
                  <strong>For other Purposes: </strong>We may use your
                  information for other purposes, such as data analysis,
                  identifying usage trends, determining the effectivveness of
                  our promotional campaigns and to evaluate and improve our
                  service, products, services, marketing and your experience.
                </li>
                <li>
                  <strong>To Contact you: </strong>To contact you by email,
                  telephone calls, SMS or other equivalent forms of electronic
                  communication, such as a mobile application's push
                  notifications regarding updates or informative communications
                  related to the functionalities, products or contracted
                  services, including the security updates, when necessary or
                  reasonable for their implementation.
                </li>
              </ol>
            </p>
            <h2>Data retention</h2>
            <p>
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies. The
              Company will also retain this Data for Data analysis purposes. The
              Data is generally retained for a shorter period of time, except
              when this data is used to strengthen the security or to improve
              the functionality of Our Service, or We are legally obligated to
              retain this data for longer time periods.
            </p>
            <h2>Data Protection</h2>
            <p>
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security. It should be noted that
              We do not store access data.
            </p>
            <h2>Information Sharing</h2>
            <ul>
              <li>
                In order to process your transactions, Appt Jobs may direct you
                to a payment gateway service provider of its own choice, which
                may have access to the Personal Information provided by you
                while making such payment.
              </li>
              <li>
                Appt Jobs does not rent, sell, or share Personal and/or Business
                Information about you with other people or with other
                non-affiliated entities, except with your consent, to provide
                services you have requested for or under the following
                circumstances:
              </li>
              <li>
                Appt Jobs may engage third party vendors and/or contractors to
                perform certain support services, who may have limited access to
                your Personal Information.
              </li>
              <li>
                Appt Jobs may share your Personal information with Government
                authorities in response to subpoenas, court orders, or other
                legal process; to establish or exercise legal rights; to defend
                against legal claims; or as otherwise required by law.
              </li>
            </ul>
            <h2>Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security
            </p>
            <h2>Changes to Our Privacy Policy</h2>
            <p>
              Any changes to our privacy policy would be duly communicated to
              you through any of our social media platforms. This Privacy Policy
              became effective on (fill this in). Any additions, deletions or
              modifications made in accordance with the Company's and the
              government’s policy changes will be notified in advance via the
              website. All material changes will be notified 30 days prior to
              such changes taking effect.
            </p>
          </Text>
        </ContentWithPaddingXl>
      </Container>
    </AnimationRevealPage>
  );
};
